[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_title = true
option_as_alt = "OnlyLeft"
dimensions = { columns = 120, lines = 50 }

[font]
size = 16
normal.family = "GoMono Nerd Font Mono"
normal.style = "Regular"
bold.family = "GoMono Nerd Font Mono"
bold.style = "Bold"
italic.family = "GoMono Nerd Font Mono"
italic.style = "Italic"

[colors.normal]
black = "0x596c77"
red = "0xeb5f59"
green = "0x8eedb3"
yellow = "0xf8d85e"
blue = "0x68c1f9"
magenta = "0xeb5181"
cyan = "0x8ff8db"
white = "0xfefefe"

[colors.bright]
black = "0xb2bcc3"
red = "0xef9084"
green = "0xc5f4cd"
yellow = "0xfae58d"
blue = "0x94d5fa"
magenta = "0xee86aa"
cyan = "0xbafaeb"
white = "0xfefefe"

[colors.primary]
foreground = "0xeceef0"
background = "0x282522"

[colors.cursor]
text = "0xe8e8e8"
cursor = "0xb69d43"

[colors.selection]
cursor = "0x657c89"
text = "0xeceef0"

[bell]
animation = "EaseOutExpo"
duration = 50

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"
mouse.enabled = true
mouse.mods = "None"
binding.key = "u"
binding.mods = "Control|Shift"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t¬"
